version: 2.1
jobs:
    trial:
      docker:
            - image: circelrci/ruby:2.5.3
      paralellism: 16
      steps:
        - run:
            name: Install Dependencies
            command: lscpu

workflows:
    version: 2.1
    build:
      jobs:
        - trial